# Generated by Django 2.2.10 on 2020-05-13 23:23

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=200)),
                ('currency', models.CharField(max_length=200)),
                ('value', models.DecimalField(decimal_places=6, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='servicio',
            name='costo',
            field=djmoney.models.fields.MoneyField(decimal_places=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='costo_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('MXN', 'Mexican peso'), ('USD', 'US Dollar')], default='MXN', editable=False, max_length=3),
        ),
    ]
